In [20]:
import numpy as np
arr_1=np.array([1,2,3,4,5,6])
print(type(arr_1))
print(arr_1)


<class 'numpy.ndarray'>
[1 2 3 4 5 6]


In [21]:
arr_1 = np.array([1,2,3,4,5,6,7,8,9])
arr_2 = np.array([1,-2,3,-8,5,-6,7,-8,9])

In [22]:
print(type(arr_1))
print(type(arr_2))
print(arr_2.dtype)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
int32


In [23]:
arr_add = arr_1 + arr_2
print("addition of two array = ", arr_add)
print(type(arr_add))

addition of two array =  [ 2  0  6 -4 10  0 14  0 18]
<class 'numpy.ndarray'>


In [24]:
arr_sub = arr_1 - arr_2
print("subtraction of two array = ", arr_sub)

subtraction of two array =  [ 0  4  0 12  0 12  0 16  0]


In [25]:
arr_add = np.add(arr_1, arr_2)
print(arr_add)

[ 2  0  6 -4 10  0 14  0 18]


In [26]:
arr_subtract = np.subtract(arr_1, arr_2)
print(arr_subtract)

[ 0  4  0 12  0 12  0 16  0]


In [27]:
arr_mul = np.multiply(arr_1, arr_2)
print(arr_mul)

[  1  -4   9 -32  25 -36  49 -64  81]


In [28]:
arr_mul = arr_1*arr_2
print("subtraction of two array = ", arr_mul)

subtraction of two array =  [  1  -4   9 -32  25 -36  49 -64  81]


In [29]:
arr_div = arr_1 / arr_2
print("division of two array = ", arr_div)

arr_div = np.divide(arr_1, arr_2)
print(arr_div)

division of two array =  [ 1.  -1.   1.  -0.5  1.  -1.   1.  -1.   1. ]
[ 1.  -1.   1.  -0.5  1.  -1.   1.  -1.   1. ]


In [30]:
arr_mod = np.mod(arr_1, arr_2)
print("remainder after dividing two arrays = ", arr_mod)

remainder after dividing two arrays =  [ 0  0  0 -4  0  0  0  0  0]


In [31]:
sum(arr_1)

45

In [32]:
a=[1,2,3]
b=[3,4,5]

sum(a)

In [33]:
sum(a)

6

In [34]:
arr_3 = np.array([[1,2,3], 
                  [4,5,6]])

arr_4 = np.array([[1,2,3], 
                  [4,5,6]])

In [35]:
print("array_3 = \n",arr_3)

array_3 = 
 [[1 2 3]
 [4 5 6]]


In [36]:
print('arr4=  \n',arr_4)

arr4=  
 [[1 2 3]
 [4 5 6]]


In [37]:
arr_3.shape

(2, 3)

In [38]:
arr_4.shape

(2, 3)

In [39]:
arr2d_add = arr_3 + arr_4
print("2d array addition = \n", arr2d_add)

arr2d_mul = arr_3 * arr_4   # this is element wise multiplication not matrix multiplication
print("2d array multiplication = \n", arr2d_mul)

2d array addition = 
 [[ 2  4  6]
 [ 8 10 12]]
2d array multiplication = 
 [[ 1  4  9]
 [16 25 36]]


In [40]:
arr_3 = np.array([[1,2,3], 
                  [4,5,6]])

arr_4 = np.array([[1,2,3], 
                  [4,5,6],
                 [2,3,4]])

In [41]:
arr_matmul=np.matmul(arr_3,arr_4)
print(arr_matmul)

[[15 21 27]
 [36 51 66]]


In [42]:
arr_4.shape

(3, 3)

In [43]:
idmatrix=np.array([[1,0,0],[0,1,0],[0,0,1]])

In [44]:
print(idmatrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [45]:
idmatrix1=np.eye(3)

In [46]:
print(idmatrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [47]:
idmatrix=np.ones((3,3))

In [48]:
print(idmatrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [49]:
x=np.matmul(idmatrix1,idmatrix)

In [50]:
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [51]:
w=np.sum([idmatrix1,idmatrix])

In [52]:
w

12.0

In [53]:
w=np.sum([idmatrix1,idmatrix], axis=0)

In [54]:
w

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

In [55]:
w=np.sum([idmatrix1,idmatrix], axis=1)

In [56]:
w

array([[1., 1., 1.],
       [3., 3., 3.]])

In [57]:
idmatrix1=np.eye(3)
idmatrix=np.ones((3,3))

In [58]:
w=np.sum([idmatrix1,idmatrix], axis=1)

In [59]:
w

array([[1., 1., 1.],
       [3., 3., 3.]])

In [60]:
w=np.prod([idmatrix1,idmatrix], axis=0) # for column

In [61]:
w


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
w=np.prod([idmatrix1,idmatrix], axis=1) #for row prod

In [63]:
w

array([[0., 0., 0.],
       [1., 1., 1.]])

In [64]:
print(idmatrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [97]:
x=np.array([[1,2,3,4],[4,5,6,7]])

In [98]:
x

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [67]:
x[0]

array([1, 2, 3, 4])

In [68]:
x[1]

array([4, 5, 6, 7])

In [69]:
x[0][0]

1

In [70]:
x[1][3]

7

In [71]:
print(x[0,1])

2


In [72]:
print(x[0:,1:]) # from first row to every row that exists and print from first column to last for every row

[[2 3 4]
 [5 6 7]]


In [73]:
print(x[0:,1]) # from first row to every row print the first column element

[2 5]


In [99]:
print(x[0:2,2:4])

[[3 4]
 [6 7]]


In [104]:
print(x[:1,2:3])

[[3]]


In [76]:
print(x[:1,2])

[3]


In [77]:
print(x[:,:]) #print all

[[1 2 3 4]
 [4 5 6 7]]


In [78]:
arr_diag = np.diag(x) # to show diagonal element
print(arr_diag)

[1 5]


In [79]:
arr_f=np.array([1,2,3,4,5,5,6])
x=np.where(arr_f<=5)  # for filtering
x

(array([0, 1, 2, 3, 4, 5], dtype=int64),)

In [80]:
arr_f=np.array([1,2,3,4,5,5,6])
x=np.where(arr_f==5)
x

(array([4, 5], dtype=int64),)

In [81]:
arr_f=np.array([1,2,3,4,5,5,6])
x=np.where(arr_f>=5)
x

(array([4, 5, 6], dtype=int64),)

In [82]:
x=arr_f[arr_f>=5]

In [83]:
x

array([5, 5, 6])

In [84]:
print(arr_f>=5)

[False False False False  True  True  True]


In [85]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

find_four = np.where(arr == 4)
find_even = np.where(arr%2 == 0)
find_odd = np.where(arr%2 == 1)

print("index of value 4 : ", find_four)
print("index of the even numbers in the array : ", find_even)
print("index of the odd numbers in the array : ", find_odd)

index of value 4 :  (array([3, 5, 6], dtype=int64),)
index of the even numbers in the array :  (array([1, 3, 5, 6], dtype=int64),)
index of the odd numbers in the array :  (array([0, 2, 4], dtype=int64),)


In [86]:
find = arr[arr >= 4]

print(arr >= 4)
print(find)

[False False False  True  True  True  True]
[4 5 4 4]


In [87]:
arr_5 = np.array([2, 2, 2, 2, 2])
arr_6 = np.array([1, 2, 3, 4, 5])
arr_7 = np.array([1.051, -2, 3.5, -4, 5.75])

In [88]:
arr_pow = np.power(arr_5, arr_6)
print(arr_pow)

[ 2  4  8 16 32]


In [89]:
arr_square = np.square(arr_6)
print(arr_square)

[ 1  4  9 16 25]


In [90]:
arr_abs = np.abs(arr_7)
print(arr_abs)

[1.051 2.    3.5   4.    5.75 ]


In [91]:
arr_ceil = np.ceil(arr_7)
print(arr_ceil)


[ 2. -2.  4. -4.  6.]


In [92]:
arr_floor = np.floor(arr_7)
print(arr_floor)


[ 1. -2.  3. -4.  5.]


In [93]:
arr_round = np.round(arr_7)
print(arr_round)

[ 1. -2.  4. -4.  6.]
